-keep class com.google.mlkit.vision.** { *; }
-keep class com.google.android.gms.internal.mlkit_vision_text_common.** { *; }
-dontwarn com.google.mlkit.vision.**
-dontwarn com.google.android.gms.internal.mlkit_vision_text_common.**
